[GH-45] contribution guidelines and code of conduct
gmggroup/omf-python pull request #62
Opened 2019-03-02 18:55 UTC by fwkoch

Before merging, we should identify a better contact email for the code of conduct than info@gmggroup.org

2019-03-02 19:03 UTC, rowanc1 requested changes
This is really awesome and well written. Looking forward to community contributions.

2019-03-02 19:03 UTC, rowanc1 commented on CONTRIBUTING.md
> +And, please, read and follow our [Code of Conduct](code_of_conduct.md).
This could be elevated rather than an after thought.

2019-03-02 19:03 UTC, rowanc1 commented on CONTRIBUTING.md
> +If the question is non-technical, follow up may happen outside of
a place to start.

2019-03-02 19:03 UTC, rowanc1 commented on CONTRIBUTING.md
> +reach out to [fwkoch](https://github.com/fwkoch) (note: this is
Should be a gmg contact email.

2019-03-02 19:03 UTC, rowanc1 commented on code_of_conduct.md
> +#### Attribution
Thanks for calling out these organizations!

2019-03-02 20:02 UTC, rowanc1 approved these changes

2019-03-04 18:31 UTC, dsanguinetti commented
This looks good on the general conduct side of things. From a GMG perspective we probably need to add something covering anti-trust as well. In the mean-time I've asked about an e-mail address.

2019-03-12 20:30 UTC, dsanguinetti commented on code_of_conduct.md
> +#### Attribution
After discussion with Heather, the e-mail address should be mine: dsanguinetti@gmggroup.org. Also, When referring to GMG it should be just GMG, not GMG group (this is coming from the communications folks...sorry!).
Thanks!
David

2019-03-15 01:16 UTC, banesullivan reviewed
On:

> If the question is non-technical, follow up may happen outside of GitHub, but this is a place to start.

What about having a Slack channel dedicated to OMF somewhere? In the @OpenGeoVis slack workspace, I've created an `omfvtk` channel for using the [OMF-Viewer](https://github.com/OpenGeoVis/omfvtk)... It might be beneficial to have something like this for new users looking for answers to simple use cases. 

Or perhaps creating a [discrourse](https://www.discourse.org) community for OMF so that questions are archived and searchable? ([ParaView](https://discourse.paraview.org) and [VTK](https://discourse.vtk.org) have really good examples of this)

2019-03-15 01:16 UTC, banesullivan commented on CONTRIBUTING.md
> +If the question is non-technical, follow up may happen outside of
Perhaps Slack or a discourse page would be appropriate?

2019-03-15 15:25 UTC, dsanguinetti commented
Hi Bane,
    We've tried Slack with the AI group in GMG, and the conclusion so
      far is that for the asynchronous sort of communication that we get
      across time zones it is better to use Basecamp or e-mail. That
      being said, we are investigating other platforms as well because
      we want to have a venue for a community of interest to share
      ideas, exactly as you've described.
    David
    
    
      
      
      
      
      
      
      
      
      
      
<!--
 /* Font Definitions */
 @font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;
	mso-font-charset:1;
	mso-generic-font-family:roman;
	mso-font-pitch:variable;
	mso-font-signature:0 0 0 0 0 0;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;
	mso-font-charset:0;
	mso-generic-font-family:swiss;
	mso-font-pitch:variable;
	mso-font-signature:-536870145 1073786111 1 0 415 0;}
@font-face
	{font-family:"DejaVu Sans";
	panose-1:2 11 6 3 3 8 4 2 2 4;
	mso-font-charset:0;
	mso-generic-font-family:swiss;
	mso-font-pitch:variable;
	mso-font-signature:-419418369 -771686913 170156073 0 511 0;}
@font-face
	{font-family:"DejaVu Sans Condensed";
	panose-1:2 11 6 6 3 8 4 2 2 4;
	mso-font-charset:0;
	mso-generic-font-family:swiss;
	mso-font-pitch:variable;
	mso-font-signature:-419418369 -771686913 170156073 0 511 0;}
 /* Style Definitions */
 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{mso-style-unhide:no;
	mso-style-qformat:yes;
	mso-style-parent:"";
	margin-top:0in;
	margin-right:0in;
	margin-bottom:8.0pt;
	margin-left:0in;
	line-height:105%;
	mso-pagination:widow-orphan;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;
	mso-ascii-font-family:Calibri;
	mso-ascii-theme-font:minor-latin;
	mso-fareast-font-family:Calibri;
	mso-fareast-theme-font:minor-latin;
	mso-hansi-font-family:Calibri;
	mso-hansi-theme-font:minor-latin;
	mso-bidi-font-family:"Times New Roman";
	mso-bidi-theme-font:minor-bidi;
	mso-fareast-language:EN-US;}
p.MsoHeader, li.MsoHeader, div.MsoHeader
	{mso-style-priority:99;
	mso-style-link:"Header Char";
	margin:0in;
	margin-bottom:.0001pt;
	mso-pagination:widow-orphan;
	tab-stops:center 3.25in right 6.5in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;
	mso-ascii-font-family:Calibri;
	mso-ascii-theme-font:minor-latin;
	mso-fareast-font-family:Calibri;
	mso-fareast-theme-font:minor-latin;
	mso-hansi-font-family:Calibri;
	mso-hansi-theme-font:minor-latin;
	mso-bidi-font-family:"Times New Roman";
	mso-bidi-theme-font:minor-bidi;
	mso-fareast-language:EN-US;}
p.MsoFooter, li.MsoFooter, div.MsoFooter
	{mso-style-priority:99;
	mso-style-link:"Footer Char";
	margin:0in;
	margin-bottom:.0001pt;
	mso-pagination:widow-orphan;
	tab-stops:center 3.25in right 6.5in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;
	mso-ascii-font-family:Calibri;
	mso-ascii-theme-font:minor-latin;
	mso-fareast-font-family:Calibri;
	mso-fareast-theme-font:minor-latin;
	mso-hansi-font-family:Calibri;
	mso-hansi-theme-font:minor-latin;
	mso-bidi-font-family:"Times New Roman";
	mso-bidi-theme-font:minor-bidi;
	mso-fareast-language:EN-US;}
p.MsoIntenseQuote, li.MsoIntenseQuote, div.MsoIntenseQuote
	{mso-style-priority:30;
	mso-style-unhide:no;
	mso-style-qformat:yes;
	mso-style-link:"Intense Quote Char";
	mso-style-next:Normal;
	margin-top:.25in;
	margin-right:.6in;
	margin-bottom:.25in;
	margin-left:.6in;
	text-align:center;
	line-height:105%;
	mso-pagination:widow-orphan;
	border:none;
	mso-border-top-alt:solid #5B9BD5 .5pt;
	mso-border-top-themecolor:accent1;
	mso-border-bottom-alt:solid #5B9BD5 .5pt;
	mso-border-bottom-themecolor:accent1;
	padding:0in;
	mso-padding-alt:10.0pt 0in 10.0pt 0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;
	mso-ascii-font-family:Calibri;
	mso-ascii-theme-font:minor-latin;
	mso-fareast-font-family:Calibri;
	mso-fareast-theme-font:minor-latin;
	mso-hansi-font-family:Calibri;
	mso-hansi-theme-font:minor-latin;
	mso-bidi-font-family:"Times New Roman";
	mso-bidi-theme-font:minor-bidi;
	color:#5B9BD5;
	mso-themecolor:accent1;
	mso-fareast-language:EN-US;
	font-style:italic;}
p.msonormal0, li.msonormal0, div.msonormal0
	{mso-style-name:msonormal;
	mso-style-unhide:no;
	mso-margin-top-alt:auto;
	margin-right:0in;
	mso-margin-bottom-alt:auto;
	margin-left:0in;
	mso-pagination:widow-orphan;
	font-size:12.0pt;
	font-family:"Times New Roman",serif;
	mso-fareast-font-family:"Times New Roman";
	mso-fareast-theme-font:minor-fareast;}
span.HeaderChar
	{mso-style-name:"Header Char";
	mso-style-priority:99;
	mso-style-unhide:no;
	mso-style-locked:yes;
	mso-style-link:Header;}
span.FooterChar
	{mso-style-name:"Footer Char";
	mso-style-priority:99;
	mso-style-unhide:no;
	mso-style-locked:yes;
	mso-style-link:Footer;}
span.IntenseQuoteChar
	{mso-style-name:"Intense Quote Char";
	mso-style-priority:30;
	mso-style-unhide:no;
	mso-style-locked:yes;
	mso-style-link:"Intense Quote";
	color:#5B9BD5;
	mso-themecolor:accent1;
	font-style:italic;}
.MsoChpDefault
	{mso-style-type:export-only;
	mso-default-props:yes;
	font-size:10.0pt;
	mso-ansi-font-size:10.0pt;
	mso-bidi-font-size:10.0pt;
	font-family:"Calibri",sans-serif;
	mso-ascii-font-family:Calibri;
	mso-ascii-theme-font:minor-latin;
	mso-fareast-font-family:Calibri;
	mso-fareast-theme-font:minor-latin;
	mso-hansi-font-family:Calibri;
	mso-hansi-theme-font:minor-latin;
	mso-bidi-font-family:"Times New Roman";
	mso-bidi-theme-font:minor-bidi;
	mso-fareast-language:EN-US;}
 /* Page Definitions */
 @page
	{mso-footnote-separator:url("David%20Sanguinetti_files/header.htm") fs;
	mso-footnote-continuation-separator:url("David%20Sanguinetti_files/header.htm") fcs;
	mso-endnote-separator:url("David%20Sanguinetti_files/header.htm") es;
	mso-endnote-continuation-separator:url("David%20Sanguinetti_files/header.htm") ecs;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;
	mso-header-margin:.5in;
	mso-footer-margin:.5in;
	mso-header:url("David%20Sanguinetti_files/header.htm") h1;
	mso-footer:url("David%20Sanguinetti_files/header.htm") f1;
	mso-paper-source:0;}
div.WordSection1
	{page:WordSection1;}
-->

      
        David Sanguinetti, M.Eng.,
            P.Eng.
        President
        Sanguinetti
              Engineering Ltd.
        Cell: 604-562-0142
      
    
    On 2019-03-14 6:16 p.m., Bane Sullivan
      wrote:
    
    
      
      @banesullivan commented on this pull request.
      On:
      
        If the question is non-technical, follow up may happen
          outside of GitHub, but this is a place to start.
      
      What about having a Slack channel dedicated to OMF somewhere?
        In the @OpenGeoVis
        slack workspace, I've created an omfvtk channel
        for using the OMF-Viewer... It might be
        beneficial to have something like this for new users looking for
        answers to simple use cases.
      Or perhaps creating a discrourse community
        for OMF so that questions are archived and searchable? (ParaView and VTK have really good examples of
        this)
      
      In CONTRIBUTING.md:
      > +
+Any questions/feedback/problems should be raised as
+[issues](https://github.com/gmggroup/omf/issues). You may comment on
+existing, relevant issues or
+[create a new issue](https://github.com/gmggroup/omf/issues/new). There
+is no restriction on what issues are "supposed to" look like; this is
+the place for anyone to voice anything about OMF. Examples include:
+- detailed technical questions around implementation
+- problems encountered when attempting to support OMF
+- confusion around the documentation
+- feature requests for the format
+- questions around the high-level goal of an open standard
+- suggestions around non-technical aspects, such as marketing and engagement
+- etc!
+
+If the question is non-technical, follow up may happen outside of

      Perhaps Slack or a discourse page would be appropriate?
      —
        You are receiving this because you commented.
        Reply to this email directly, view it on Gi [...]

2019-03-22 20:47 UTC, merged