removed origin from project and project element Geometry
gmggroup/omf-python pull request #68
Opened 2019-03-26 12:20 UTC by michiboo

Hi I remove origin from project and project element, and add corner to surface and volume class.

2019-03-27 10:35 UTC, fwkoch requested changes
Thanks for the PR! Can you also update the tests for these changes so the Travis build passes?

2019-03-27 10:35 UTC, fwkoch commented on omf/surface.py
> +        'Origin of the Mesh relative to origin of the Project',
Please update these doc strings since there is no longer a project origin. Maybe "relative to the coordinate reference system" instead?

2019-04-21 19:22 UTC, michiboo commented
Hi sorry for the delay! I updated it but I notice the problem seem to be already fixed?

2019-09-11 17:30 UTC, fwkoch commented
Thanks again for the contribution - I'm going to close this PR as the relevant changes were rolled into other big, structural changes.

Keep on the lookout, though. Once the initial release of v2 is out, there should be other smaller, incremental fixes looking for contributors.

2019-09-11 17:30 UTC, closed without merging